remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme 

title: [DeskToys]
description: [A collection of useful desktop tools.]
show_downloads: [true]

include:
  - publish
  - changelogs

